name = "hex-berlekamp-mathlib"
defaultTargets = ["HexBerlekampMathlib", "HexBerlekampMathlibTests"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexBerlekamp"
git = "https://github.com/leanprover/hex-berlekamp.git"
rev = "588422f093eed407b03b65398b2c1bbc4595e4d6"

[[require]]
name = "HexPolyMathlib"
git = "https://github.com/leanprover/hex-poly-mathlib.git"
rev = "e17fbabc5d782679c3c55838ff2ed0e15db88631"

[[require]]
name = "HexModArithMathlib"
git = "https://github.com/leanprover/hex-mod-arith-mathlib.git"
rev = "a90f0f2add88de1d214a169d30048b095f1dcdd2"

[[require]]
name = "HexPolyFpMathlib"
git = "https://github.com/leanprover/hex-poly-fp-mathlib.git"
rev = "4cf1484372c505472e554dbcfade0a415bff9820"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexBerlekampMathlib"

[[lean_lib]]
name = "HexBerlekampMathlibTests"
globs = ["HexBerlekampMathlib.FactorPolyTests"]
